### PR TITLE
Better member expression handling to support mixins.

### PR DESCRIPTION
**Pull request by tonysherbondy**
Can handle member expressions of types:
- Ember.Controller.extend
- App.FunMixin

Also, make the member expression visitor more clear with helper function.

@fivetanley @igorT

### CODE REVIEW

**Comment by tonysherbondy** [comment]
@igorT @fivetanley bump...

**Comment by fivetanley** [comment]
Seems great if you can resolve the rebase conflicts. Sorry I took so long getting to this!

**Comment by fivetanley** [comment]
@tonysherbondy I added you to the collaborators so you should be able to merge this once the conflicts are resolved. Thanks!

**Comment by tonysherbondy** [comment]
Thanks for the commit access. What is your policy for upgrading the release number?

**Comment by fivetanley** [comment]
Generaly semver. So this looks like a bugfix to me, seems good to bump the last number. If you can have an npm account I can give you publish there as well

**Comment by tonysherbondy** [comment]
I agree, bugfix, seems right.
Done. Same username.

**Pull request merged**
