### PR TITLE
Added support for components

### PR DESCRIPTION
**Pull request by kiwiupover**
With a tests for a component and a service.

Also updated the readme.

### CODE REVIEW

**Comment by kiwiupover** [comment]
The components work out of the box. I was going to add a test services as well but they are also being migrated as expected.

**Comment by igorT** [comment]
Please do, I'm a bit confused why it works without it

**Comment by kiwiupover** [comment]
@igorT this should be ready to go

**Comment by igorT** [comment]
Thanks!

**Pull request merged**
